controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    wheels_per_side: 2
    left_wheel_names: [ "rear_left_wheel_joint" ,"front_left_wheel_joint" ]
    right_wheel_names: [ "rear_right_wheel_joint", "front_right_wheel_joint" ]

    wheel_separation: 0.32
    wheel_separation_multiplier: 1.6 #TODO revise
    wheel_radius: 0.0395
    
    position_feedback: true
    open_loop: false
    cmd_vel_timeout: 0.1
    base_frame_id: base_link

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.2
    linear.x.min_velocity: -0.2

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 0.3
    angular.z.min_velocity: -0.3