<?xml version="1.0"?>
<robot name="ugv" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find ugv_description)/gazebo/common_inertias.xacro" />

    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_thickness" value="0.0369" />
    <xacro:property name="wheel_mass" value="0.05" />

    <xacro:property name="chassis_length" value="0.34" />
    <xacro:property name="chassis_width" value="0.285" />
    <xacro:property name="chassis_height" value="0.02" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="chassis_offset_z" value="${wheel_radius}" />

    <xacro:property name="lidar_radius" value="0.02" />
    <xacro:property name="lidar_thickness" value="0.1" />
    <xacro:property name="lidar_mass" value="0.05" />


    <xacro:property name="edge_to_motor_mount" value="0.04" />
    <xacro:property name="motor_mount_width" value="0.0417" />
    <xacro:property name="motor_shaft_to_edge_x" value="${edge_to_motor_mount+motor_mount_width/2}" />

    <xacro:property name="wheel_offset_x" value="${chassis_length/2-motor_shaft_to_edge_x}" />
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2 + 0.0029}"/>
    <xacro:property name="wheel_offset_z" value="0.01" />

    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
                <material name="orange" />
            </visual>
            <collision>
                <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
                radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 ${chassis_offset_z}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${chassis_offset_z}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}"
            z="${chassis_height}">
            <origin rpy="0 0 0" xyz="0 0 ${chassis_offset_z}"/>
        </xacro:inertial_box>
    </link>

    <link name="base_footprint" />

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <xacro:wheel prefix="front_right"  />


    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_radius}" />
        <axis xyz="0.0 1.0 0.0" />
    </joint>


    <xacro:wheel prefix="front_left" />

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_radius}" />
        <axis xyz="0.0 1.0 0.0" />
    </joint>

    <xacro:wheel prefix="rear_right"  />

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel" />
        <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_radius}" />
        <axis xyz="-0.0 1.0 0.0" />
    </joint>

    <xacro:wheel prefix="rear_left" />

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel" />
        <origin xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_radius}" />
        <axis xyz="0.0 1.0 0.0" />
    </joint>

    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_thickness}" />     </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_thickness}" />    
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${lidar_mass}" length="${lidar_thickness}"
            radius="${lidar_radius}">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <joint name="lidar_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="${chassis_length/2-lidar_radius} 0 ${chassis_offset_z+lidar_thickness/2}" rpy="0 0 0"/>
    </joint> 

</robot>